image:
  file: .gitpod.Dockerfile
tasks:
  - name: Senv
    init: |
      rustup install nightly
    command: |
      gp open README.md
  - name: Sval
    init: |
      solana-keygen new  --no-bip39-passphrase
      solana config set --url localhost
      solana-test-validator
  - name: Shost
    init: |
      npm install
      npm run build:program-rust
      solana airdrop 1000
      solana program deploy /workspace/solana-escrow/dist/program/solana_escrow.so
  - name: Sweb
    init: |
      cd src/client
      npm install
      npm run serve   

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
ports:
  - port: 1024
    onOpen: ignore
  - port: 8899
    onOpen: ignore
  - port: 8900
    onOpen: ignore
  - port: 9900
    onOpen: ignore
